package analyzer

import (
	"os"
	"path/filepath"
	"testing"
)

func TestGeneratedFilesSkipped(t *testing.T) {
	dir := t.TempDir()
	generated := `// Code generated by test; DO NOT EDIT.
package p

type God struct{}

func (g *God) M1() {}
func (g *God) M2() {}
func (g *God) M3() {}
func (g *God) M4() {}
func (g *God) M5() {}
func (g *God) M6() {}
func (g *God) M7() {}
func (g *God) M8() {}
func (g *God) M9() {}
func (g *God) M10() {}
func (g *God) M11() {}
`
	if err := os.WriteFile(filepath.Join(dir, "generated.go"), []byte(generated), 0o644); err != nil {
		t.Fatal(err)
	}
	pkgs := loadWorkspaceDir(t, dir, false, "auto")
	issues := Run(pkgs, DefaultConfig(), map[Rule]bool{RuleSRP: true, RuleISP: true, RuleDIP: true})
	for _, issue := range issues {
		t.Fatalf("generated file produced issue: %v", issue)
	}
}

func TestIssuesIncludeEndRange(t *testing.T) {
	pkgs := loadWorkspaceDir(t, testdataDir(t, "violations"), false, "types")
	issues := Run(pkgs, DefaultConfig(), map[Rule]bool{RuleSRP: true, RuleISP: true, RuleDIP: true, RuleOCP: true, RuleLSP: true})
	if len(issues) == 0 {
		t.Fatal("expected violations fixture to produce issues")
	}
	found := false
	for _, issue := range issues {
		if issue.End.Line > 0 && issue.End.Offset > issue.Pos.Offset {
			found = true
			break
		}
	}
	if !found {
		t.Fatalf("expected at least one issue with end range, got %d issues", len(issues))
	}
}
